# a program that print the initial big letters of my name
print("\t\t\tPatrick MUSHIMIYE")
print("\b")
print("  PPPPPPP\t\t\t\t\tMM            MM")
print("pp         p\t\t\t\tMM MM     MM  MM")
print("pp        p\t\t\t\t\tMM    MM      MM")
print("pp  p   p\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
print("pp\t\t\t\t\t\t\tMM            MM")
